dbt_lh:
  outputs:

    dev:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: admin
      database: iceberg
      host: localhost
      port: 8080
      schema: sandbox
      threads: 1

  target: dev
